FROM node:18 AS BUILD_IMAGE

RUN wget https://gobinaries.com/tj/node-prune
RUN sh node-prune

WORKDIR /app

COPY package.json index.js .env /app/
COPY bots /app/bots

# install 
RUN npm install 

# remove development dependencies
RUN npm prune --production

# run node prune
RUN /usr/local/bin/node-prune

FROM node:18-alpine

WORKDIR /app

# copy from build image
COPY --from=BUILD_IMAGE /app ./

ENV DEBUG msteams

EXPOSE 3987

CMD [ "npm", "start" ]
